### PR TITLE
Fix #105

### LINKED ISSUE #105: format() function is not showing correct timezone
According to docs at [github](https://github.com/xx45/dayjs#format), the function `dayjs().format()` (without any arguments) should return a timestamp with timezone like "2018-05-06T14:31:02+05:30" (My timezone is +5:30). But instead it's returning "2018-05-06T14:31:020500:00". I checked with the code, even test for `Format no formatStr` is failing with : 
```Format no formatStr

    expect(received).toBe(expected) // Object.is equality

    Expected value to be:
      "2018-05-06T14:26:00+05:30"
    Received:
      "2018-05-06T14:26:000500:00"
```

### PR DESCRIPTION
**Pull request by Imperat**
padZoneStr function from utils.js file was been rewritten
to support timezones with non-zero minutes. GMT +5:30 for example.

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -4,15 +4,13 @@ export const padStart = (string, length, pad) => {
...
-    replacer = '$10$200'
-  } else {
-    replacer = '$1$200'
-  }
-  return padStart(String(hour).replace(/^(.)?(\d)/, replacer), 5, '+')
+export const padZoneStr = (negMinuts) => {
+  const minutes = Math.abs(negMinuts)
+  const sign = negMinuts <= 0 ? '+' : '-'
+  const hourOffset = Math.floor(minutes / 60)
+  const minuteOffset = minutes - (hourOffset * 60)
```
Comment (iamkun) [inline src/utils.js]: `minutes % 60` better ?

**Comment by Imperat** [comment]
Hi, @iamkun. I update my commit according to your notes. Thank you!

**Comment by iamkun** [comment]
Cool. THX
